#include<stdio.h>
#include<conio.h>
#include<string.h>
void main()
{
	char s[100], s1[100];
	clrscr();

	printf("Enter String : ");
	gets(s);

	//printf("strlen -> %d \n", strlen(s));
	//printf("strupr -> %s \n", strupr(s));
	//printf("strlwr -> %s \n", strlwr(s));
	//printf("strrev -> %s \n", strrev(s));
	//printf("strcat -> %s \n", strcat(s," test"));
	//printf("strcmp -> %d \n", strcmp(s,"hello"));
	//strcpy(s1, s);
	//printf("strcpy -> %s \n", s1);

	getch();
}